name: Daily Twitter Check

on:
  #-----Unschedule for now as snscrape is not working, hence scheduling is commented out----
  # schedule:
  #   - cron: "0 20 * * *"  # Every day at 20:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run bot
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_PROVIDER: ${{ secrets.EMAIL_PROVIDER }}
      run: python main.py
